<a href="https://colab.research.google.com/github/2403a54123-web/NLP/blob/main/2403A54123_NLP_LabAssignment_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data=pd.read_csv('/content/Dataset.csv')

In [3]:
print(data)

                      Football is popular worldwide.  Unnamed: 1
0                Basketball players train very hard.         NaN
1                 The Olympics unite many countries.         NaN
2                Athletes need strong mental health.         NaN
3      eSports competitions attract young audiences.         NaN
4            Children learn teamwork through sports.         NaN
5                  Elections allow citizens to vote.         NaN
6               Governments create laws for society.         NaN
7               Climate change affects many nations.         NaN
8          People debate immigration policies often.         NaN
9           Democracy requires active participation.         NaN
10       Leaders make important political decisions.         NaN
11  Doctors promote preventive healthcare practices.         NaN
12        Eating vegetables improves overall health.         NaN
13                   Exercise keeps the body strong.         NaN
14                Vaccine

In [4]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab') # Added to resolve LookupError

documents = [
"Football is popular worldwide.",
"Basketball players train very hard.",
"The Olympics unite many countries.",
"Athletes need strong mental health.",
"eSports competitions attract young audiences.",
"Children learn teamwork through sports.",
"Elections allow citizens to vote.",
"Governments create laws for society.",
"Climate change affects many nations.",
"People debate immigration policies often.",
"Democracy requires active participation.",
"Leaders make important political decisions.",
"Doctors promote preventive healthcare practices.",
"Eating vegetables improves overall health.",
"Exercise keeps the body strong.",
"Vaccines prevent serious diseases.",
"Mental health is very important.",
"Hospitals provide emergency medical care.",
"Technology changes daily human life.",
"Computers process information very quickly.",
"Artificial intelligence improves many services.",
"Cybersecurity protects online personal data.",
"Smartphones connect people globally.",
"Renewable energy supports clean power."
]

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return " ".join(tokens)

cleaned_documents = [preprocess(doc) for doc in documents]

print(cleaned_documents)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


['football popular worldwide', 'basketball player train hard', 'olympics unite many country', 'athlete need strong mental health', 'esports competition attract young audience', 'child learn teamwork sport', 'election allow citizen vote', 'government create law society', 'climate change affect many nation', 'people debate immigration policy often', 'democracy requires active participation', 'leader make important political decision', 'doctor promote preventive healthcare practice', 'eating vegetable improves overall health', 'exercise keep body strong', 'vaccine prevent serious disease', 'mental health important', 'hospital provide emergency medical care', 'technology change daily human life', 'computer process information quickly', 'artificial intelligence improves many service', 'cybersecurity protects online personal data', 'smartphones connect people globally', 'renewable energy support clean power']


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "Football is popular worldwide",
    "Artificial intelligence improves many services",
    "Doctors promote preventive healthcare practices"
]

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(documents)

print("Feature Names:\n", vectorizer.get_feature_names_out())
print("\nTF-IDF Matrix:\n", tfidf_matrix.toarray())


Feature Names:
 ['artificial' 'doctors' 'football' 'healthcare' 'improves' 'intelligence'
 'is' 'many' 'popular' 'practices' 'preventive' 'promote' 'services'
 'worldwide']

TF-IDF Matrix:
 [[0.        0.        0.5       0.        0.        0.        0.5
  0.        0.5       0.        0.        0.        0.        0.5      ]
 [0.4472136 0.        0.        0.        0.4472136 0.4472136 0.
  0.4472136 0.        0.        0.        0.        0.4472136 0.       ]
 [0.        0.4472136 0.        0.4472136 0.        0.        0.
  0.        0.        0.4472136 0.4472136 0.4472136 0.        0.       ]]


In [6]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Example documents (can use your full dataset)
documents = [
    "Football is popular worldwide",
    "Basketball players train very hard",
    "Doctors promote preventive healthcare practices",
    "Artificial intelligence improves many services",
    "Exercise keeps the body strong"
]

# Convert to TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

# Compute cosine similarity matrix
similarity_matrix = cosine_similarity(tfidf_matrix)

# Print similarity scores
print("Cosine Similarity Matrix:\n")
print(np.round(similarity_matrix, 3))


Cosine Similarity Matrix:

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 5 example documents
documents = [
    "Football is popular worldwide.",
    "Athletes need strong mental health.",
    "Doctors promote preventive healthcare practices.",
    "Technology changes daily human life.",
    "Artificial intelligence improves many services."
]

# Simple document names
doc_names = ["D1", "D2", "D3", "D4", "D5"]

# Preprocess: lowercase + remove punctuation
def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    return text

cleaned_docs = [preprocess(doc) for doc in documents]

# Convert to TF-IDF vectors
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(cleaned_docs)

# Compute Cosine Similarity
similarity_matrix = cosine_similarity(tfidf_matrix)

# Convert to DataFrame with document names
similarity_df = pd.DataFrame(similarity_matrix, index=doc_names, columns=doc_names)

# Print similarity matrix
print("Cosine Similarity Matrix:\n")
print(similarity_df.round(2))


Cosine Similarity Matrix:

     D1   D2   D3   D4   D5
D1  1.0  0.0  0.0  0.0  0.0
D2  0.0  1.0  0.0  0.0  0.0
D3  0.0  0.0  1.0  0.0  0.0
D4  0.0  0.0  0.0  1.0  0.0
D5  0.0  0.0  0.0  0.0  1.0


In [8]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# 5 example documents
documents = [
    "Football is popular worldwide.",
    "Athletes need strong mental health.",
    "Doctors promote preventive healthcare practices.",
    "Technology changes daily human life.",
    "Artificial intelligence improves many services."
]

doc_names = ["D1", "D2", "D3", "D4", "D5"]

# Preprocess: lowercase + remove punctuation
def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    return text

cleaned_docs = [preprocess(doc) for doc in documents]

# --- Cosine Similarity (for comparison) ---
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(cleaned_docs)
cosine_sim = cosine_similarity(tfidf_matrix)
cosine_df = pd.DataFrame(cosine_sim, index=doc_names, columns=doc_names)

# --- Jaccard Similarity ---
def jaccard_similarity(doc1, doc2):
    set1 = set(doc1.split())
    set2 = set(doc2.split())
    return len(set1 & set2) / len(set1 | set2)

# Compute Jaccard similarity matrix
jaccard_matrix = [[jaccard_similarity(d1, d2) for d2 in cleaned_docs] for d1 in cleaned_docs]
jaccard_df = pd.DataFrame(jaccard_matrix, index=doc_names, columns=doc_names)

# Print both matrices
print("Cosine Similarity Matrix:\n")
print(cosine_df.round(2))
print("\nJaccard Similarity Matrix:\n")
print(jaccard_df.round(2))


Cosine Similarity Matrix:

     D1   D2   D3   D4   D5
D1  1.0  0.0  0.0  0.0  0.0
D2  0.0  1.0  0.0  0.0  0.0
D3  0.0  0.0  1.0  0.0  0.0
D4  0.0  0.0  0.0  1.0  0.0
D5  0.0  0.0  0.0  0.0  1.0

Jaccard Similarity Matrix:

     D1   D2   D3   D4   D5
D1  1.0  0.0  0.0  0.0  0.0
D2  0.0  1.0  0.0  0.0  0.0
D3  0.0  0.0  1.0  0.0  0.0
D4  0.0  0.0  0.0  1.0  0.0
D5  0.0  0.0  0.0  0.0  1.0


In [10]:
import nltk
from nltk.corpus import wordnet as wn
import re

# Download WordNet if not already
nltk.download('wordnet')
nltk.download('omw-1.4')

# 10 documents
docs = [
    "Football is popular worldwide.",
    "Athletes need strong mental health.",
    "Doctors promote preventive healthcare practices.",
    "Eating vegetables improves overall health.",
    "Exercise keeps the body strong.",
    "Technology changes daily human life.",
    "Computers process information very quickly.",
    "Artificial intelligence improves many services.",
    "Smartphones connect people globally.",
    "Renewable energy supports clean power."
]

doc_names = [f"D{i}" for i in range(1, 11)]

# Preprocess: lowercase + remove punctuation
def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    return text

cleaned_docs = [preprocess(doc) for doc in docs]

# Function to compute average Wu-Palmer similarity between two sentences
def sentence_similarity(sent1, sent2):
    words1 = sent1.split()
    words2 = sent2.split()
    sims = []
    for w1 in words1:
        # Ensure we only consider nouns for WordNet similarity if pos=wn.NOUN is used
        # Or remove pos=wn.NOUN to allow other parts of speech if desired
        syns1 = wn.synsets(w1, pos=wn.NOUN)
        if not syns1:
            continue
        for w2 in words2:
            syns2 = wn.synsets(w2, pos=wn.NOUN)
            if not syns2:
                continue
            # Get the first synset for simplicity; more advanced approaches might try all combinations
            sim = syns1[0].wup_similarity(syns2[0])
            if sim:
                sims.append(sim)
    if sims:
        return sum(sims)/len(sims)
    else:
        return 0

# Example 10 sentence pairs defined by their indices in cleaned_docs
sentence_pairs_with_indices = [
    (0, 1),  # D1 ↔ D2
    (1, 2),  # D2 ↔ D3
    (2, 3),  # D3 ↔ D4
    (3, 4),  # D4 ↔ D5
    (4, 1),  # D5 ↔ D2
    (5, 6),  # D6 ↔ D7
    (6, 7),  # D7 ↔ D8
    (7, 8),  # D8 ↔ D9
    (8, 5),  # D9 ↔ D6
    (9, 5)   # D10 ↔ D6
]

# Compute semantic similarity
for idx1, idx2 in sentence_pairs_with_indices:
    s1 = cleaned_docs[idx1]
    s2 = cleaned_docs[idx2]
    d1 = doc_names[idx1]
    d2 = doc_names[idx2]
    sim = sentence_similarity(s1, s2)
    print(f"{d1} ↔ {d2} | Average Wu-Palmer Similarity: {sim:.2f}")


D1 ↔ D2 | Average Wu-Palmer Similarity: 0.19
D2 ↔ D3 | Average Wu-Palmer Similarity: 0.23
D3 ↔ D4 | Average Wu-Palmer Similarity: 0.20
D4 ↔ D5 | Average Wu-Palmer Similarity: 0.21
D5 ↔ D2 | Average Wu-Palmer Similarity: 0.23
D6 ↔ D7 | Average Wu-Palmer Similarity: 0.30
D7 ↔ D8 | Average Wu-Palmer Similarity: 0.35
D8 ↔ D9 | Average Wu-Palmer Similarity: 0.35
D9 ↔ D6 | Average Wu-Palmer Similarity: 0.27
D10 ↔ D6 | Average Wu-Palmer Similarity: 0.27


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [11]:
import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.corpus import wordnet as wn

# Ensure WordNet is downloaded
nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)

# Using the cleaned_docs and doc_names from previous cells for consistency
# cleaned_docs was last updated in cell OItZdvFd_JS_
# doc_names was last updated in cell OItZdvFd_JS_

print("Comparing Cosine, Jaccard, and WordNet-based Similarities:\n")

# --- 1. Cosine Similarity (TF-IDF based) ---
print("--- Cosine Similarity Matrix (TF-IDF based) ---")
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(cleaned_docs)
cosine_sim_matrix = cosine_similarity(tfidf_matrix)
cosine_df = pd.DataFrame(cosine_sim_matrix, index=doc_names, columns=doc_names)
print(cosine_df.round(2))
print("\n")

# --- 2. Jaccard Similarity ---
print("--- Jaccard Similarity Matrix ---")
def jaccard_similarity(doc1, doc2):
    set1 = set(doc1.split())
    set2 = set(doc2.split())
    if not (set1 | set2): # Handle case where both sets are empty
        return 0.0
    return len(set1 & set2) / len(set1 | set2)

jaccard_matrix = [[jaccard_similarity(d1, d2) for d2 in cleaned_docs] for d1 in cleaned_docs]
jaccard_df = pd.DataFrame(jaccard_matrix, index=doc_names, columns=doc_names)
print(jaccard_df.round(2))
print("\n")

# --- 3. WordNet-based Similarity (Wu-Palmer) ---
print("--- WordNet-based Wu-Palmer Similarity for selected pairs ---")

def sentence_similarity_wup(sent1, sent2):
    words1 = sent1.split()
    words2 = sent2.split()
    sims = []
    for w1 in words1:
        syns1 = wn.synsets(w1, pos=wn.NOUN)
        if not syns1:
            continue
        for w2 in words2:
            syns2 = wn.synsets(w2, pos=wn.NOUN)
            if not syns2:
                continue
            sim = syns1[0].wup_similarity(syns2[0])
            if sim:
                sims.append(sim)
    if sims:
        return sum(sims)/len(sims)
    else:
        return 0

# Using the same sentence pairs as in cell OItZdvFd_JS_ for comparison
sentence_pairs_with_indices = [
    (0, 1),  # D1 ↔ D2
    (1, 2),  # D2 ↔ D3
    (2, 3),  # D3 ↔ D4
    (3, 4),  # D4 ↔ D5
    (4, 1),  # D5 ↔ D2
    (5, 6),  # D6 ↔ D7
    (6, 7),  # D7 ↔ D8
    (7, 8),  # D8 ↔ D9
    (8, 5),  # D9 ↔ D6
    (9, 5)   # D10 ↔ D6
]

for idx1, idx2 in sentence_pairs_with_indices:
    s1 = cleaned_docs[idx1]
    s2 = cleaned_docs[idx2]
    d1 = doc_names[idx1]
    d2 = doc_names[idx2]
    sim = sentence_similarity_wup(s1, s2)
    print(f"{d1} ↔ {d2} | Average Wu-Palmer Similarity: {sim:.2f}")


Comparing Cosine, Jaccard, and WordNet-based Similarities:

--- Cosine Similarity Matrix (TF-IDF based) ---
      D1    D2   D3    D4    D5   D6   D7    D8   D9  D10
D1   1.0  0.00  0.0  0.00  0.00  0.0  0.0  0.00  0.0  0.0
D2   0.0  1.00  0.0  0.16  0.18  0.0  0.0  0.00  0.0  0.0
D3   0.0  0.00  1.0  0.00  0.00  0.0  0.0  0.00  0.0  0.0
D4   0.0  0.16  0.0  1.00  0.00  0.0  0.0  0.18  0.0  0.0
D5   0.0  0.18  0.0  0.00  1.00  0.0  0.0  0.00  0.0  0.0
D6   0.0  0.00  0.0  0.00  0.00  1.0  0.0  0.00  0.0  0.0
D7   0.0  0.00  0.0  0.00  0.00  0.0  1.0  0.00  0.0  0.0
D8   0.0  0.00  0.0  0.18  0.00  0.0  0.0  1.00  0.0  0.0
D9   0.0  0.00  0.0  0.00  0.00  0.0  0.0  0.00  1.0  0.0
D10  0.0  0.00  0.0  0.00  0.00  0.0  0.0  0.00  0.0  1.0


--- Jaccard Similarity Matrix ---
      D1    D2   D3    D4    D5   D6   D7    D8   D9  D10
D1   1.0  0.00  0.0  0.00  0.00  0.0  0.0  0.00  0.0  0.0
D2   0.0  1.00  0.0  0.11  0.11  0.0  0.0  0.00  0.0  0.0
D3   0.0  0.00  1.0  0.00  0.00  0.0  0.0  0